# Generated by Django 2.2.6 on 2020-03-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0060_auto_20200328_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenext',
            name='alt',
            field=models.CharField(blank=True, help_text='описание картинки', max_length=150, verbose_name='Alt картинка'),
        ),
    ]
