# Generated by Django 2.2.6 on 2020-06-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0063_pictures_alt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navconstruct',
            options={'ordering': ['order'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Основное меню'},
        ),
        migrations.AddField(
            model_name='navconstruct',
            name='order',
            field=models.IntegerField(blank=True, help_text='последователность отображения в меню', null=True, verbose_name='Порядок в меню'),
        ),
    ]
