# Generated by Django 2.2.6 on 2020-06-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0064_auto_20200603_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predescription', models.TextField(blank=True, help_text='Краткое описание', verbose_name='Краткое описание')),
                ('namecategory', models.CharField(help_text='Название категории', max_length=30, verbose_name='Название категории')),
                ('caregory', models.CharField(help_text='Категория', max_length=100, verbose_name='Категория')),
                ('name', models.ForeignKey(help_text='привязка к примеру', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortnew', to='information.Example', verbose_name='Пример')),
            ],
            options={
                'verbose_name': 'Краткая информация примера',
                'verbose_name_plural': 'Краткая информация примера',
            },
        ),
    ]
