# Generated by Django 2.2.6 on 2020-06-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0065_shortnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortnew',
            name='predescription',
        ),
    ]
