# Generated by Django 2.2.6 on 2020-06-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0066_remove_shortnew_predescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='full name')),
            ],
        ),
    ]
