# Generated by Django 2.2.6 on 2020-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0068_person_name1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name1',
            field=models.CharField(blank=True, max_length=50, verbose_name='full name1'),
        ),
    ]
