# Generated by Django 2.2.6 on 2020-06-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0069_auto_20200615_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name0',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, verbose_name='РЕШЕНИЕ URETEK'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name1',
            field=models.CharField(blank=True, max_length=50, verbose_name='ТРАДИЦИОННОЕ РЕШЕНИЕ'),
        ),
    ]
