# Generated by Django 2.2.6 on 2020-06-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0070_auto_20200615_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenext',
            name='order',
            field=models.IntegerField(blank=True, help_text='последователность отображения в меню', null=True, verbose_name='Порядок в меню'),
        ),
    ]
